USE QLKHO
GO
CREATE TABLE Ton(
    MaVT NVARCHAR(20) PRIMARY KEY NOT NULL,
    TenVT NVARCHAR(20) NOT NULL,
    SoLuongT INT NOT NULL
)
GO
CREATE TABLE Nhap(
    SoHDN NVARCHAR(20) PRIMARY KEY NOT NULL,
    MaVT NVARCHAR(20) NOT NULL,
    SoLuongN INT NOT NULL,
    DonGiaN INT NOT NULL,
    NgayN DATETIME,
    CONSTRAINT FK_Nhap_MaVT FOREIGN KEY (MaVT) REFERENCES Ton(MaVT)
)
GO
CREATE TABLE Xuat(
    SoHDX NVARCHAR PRIMARY KEY NOT NULL,
    MaVT NVARCHAR(20) NOT NULL,
    SoLuongX INT NOT NULL,
    DonGiaX INT NOT NULL,
    NgayX DATETIME,
    CONSTRAINT FK_Xuat_MaVT FOREIGN KEY (MaVT) REFERENCES Ton(MaVT)
)
GO
DROP TABLE Nhap
DROP TABLE Xuat

